### PR TITLE
[PR] module optimize

### PR DESCRIPTION
**Pull request by mingbujian**
1、reduce the time overhead of the module

### CODE REVIEW

**Comment by ketoo** [comment]
Your PR shows that the variable NFIModule:: m_bIsExecute will decide the module be executed or not, but actually we have config file to let NF knows a plugin can be executed or not. So is that necessary to add a new variable for the similar feature and let developers change it by hard code?

**Comment by mingbujian** [comment]
Adding this tag can make developers realize that some modules do not need to be ticked every time, but they can still obtain modules from the plugin management and use them (after all, some modules only provide interfaces). For example: m_pModule = pPluginManager->FindModule<NFIHelloWorld4Module>();

**Comment by ketoo** [comment]
Great idea!

I think most of these modules don't need to be ticked every time. Maybe only the schedule module and some network modules.

**Comment by mingbujian** [comment]
Among many new functional modules, of the 10 additional functional modules, only 2 need to be ticked. Since the tick is too low-level, I hope to optimize it.

**Comment by ketoo** [comment]
> Among many new functional modules, of the 10 additional functional modules, only 2 need to be ticked. Since the tick is too low-level, I hope to optimize it.

Yes, I agree with you, could you please let the default value is false for variable m_bIsExecute as most of the time it should be false. Besides I will modify the constructor for the modules which need to be ticked, you could do the same if you like to do.

**Comment by mingbujian** [comment]
Yes, whether the module is ticked should be set to flase. Already processed

**Pull request merged**
