### PR TITLE
[PR]schedule optimize

### PR DESCRIPTION
**Pull request by mingbujian**
A little modification

### CODE REVIEW

**Comment by ketoo** [comment]
Hi, thanks for your PR.

Some questions for this PR:

May I know the reason to remove the code below?
``
if (scheduleElement->mnRemainCount != 0)
{
    TickElement element;
    element.scheduleName = scheduleElement->mstrScheduleName;
    element.triggerTime = scheduleElement->mnTriggerTime;
    element.self = scheduleElement->self;

    elements.push_back(element);
}

for (auto& item : elements)
 {
    mScheduleMap.insert(item);
 }
``

This code is to tick the heartbeat event repeatedly if we want (RemainCount != 0).

Thanks.

**Comment by mingbujian** [comment]
My modification is the same as your logic. In other words, the overhead of deleting and inserting can be omitted.

**Comment by ketoo** [comment]
If we don't reinsert the TickElement into mScheduleMap again, how can we call the code below to sort all tick elements by time?

```
	bool operator< (const TickElement& b) const
	{
		return this->triggerTime < b.triggerTime;
	}
```

If we don't re-sort the elements that means we the tick elements behind the first item in mScheduleMap will never be ticked as we will break the loop.

**Comment by mingbujian** [comment]
1) I reviewed the code and added the missing ++it;
2) Regarding the sorting problem, because the bottom layer is a red-black tree, after deleting a node, the balance of the tree will be automatically adjusted, and the predecessor and successor of node on the tree will not change.
Below is my test code and output:
#include<iostream>
#include<set>
#include<algorithm>
class TickElement
{
public:
    TickElement(int nkey) :key(nkey),data(nkey*2) {}

    bool operator< (const TickElement& b) const
    {
        return this->key < b.key;
    }

    int key;
    int data;
};
void test(std::multiset<TickElement>& setTest, int nCondition)
{
    std::cout << "\nBefore data:" << std::endl;
    
    for_each(setTest.begin(), setTest.end(), [](const TickElement& a) {std::cout <<"{" << a.key << "," << a.data << "}; "; });

    for (auto it = setTest.begin(); it != setTest.end();)
    {
        if (it->key < nCondition)
            it = setTest.erase(it);
        else
            it++;
    }

    std::cout << "\nEnd data:" << std::endl;
    for_each(setTest.begin(), setTest.end(), [](const TickElement& a) {std::cout << "{" << a.key << "," << a.data << "}; "; });
}
int main()
{
    std::multiset<TickElement> setTest = { 7,6,5,3,6,9,9,2,3,4,1,1,1,3,5 };
    test(setTest, 3);
    test(setTest, 6);
    return 0;
}

Output:
Before data:
{1,2}; {1,2}; {1,2}; {2,4}; {3,6}; {3,6}; {3,6}; {4,8}; {5,10}; {5,10}; {6,12}; {6,12}; {7,14}; {9,18}; {9,18};
End data:
{3,6}; {3,6}; {3,6}; {4,8}; {5,10}; {5,10}; {6,12}; {6,12}; {7,14}; {9,18}; {9,18};

Before data:
{3,6}; {3,6}; {3,6}; {4,8}; {5,10}; {5,10}; {6,12}; {6,12}; {7,14}; {9,18}; {9,18};
End data:
{6,12}; {6,12}; {7,14}; {9,18}; {9,18};

**Pull request closed without merging**
